### ISSUE TITLE
TLDR and demo on transaction types

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/docs#1129]
There are multiple transaction types on Celo. Some are newly introduced, some exist since genesis, some are slowly phased out. 

Write up the different transaction types, some context on them, where they are supported currently and their plans in the future (continue to support vs stop supporting)

_Edit: Explainer is currently published here: https://github.com/celo-org/txtypes_

**Comment by 0xarthurxyz** [comment]
Currently waiting for response from @carterqw2 to my [questions on Slack](https://celo-org.slack.com/archives/CNJ7KTHQU/p1697427973015479).

**Comment by 0xarthurxyz** [comment]
Got the [answers I needed](https://celo-org.slack.com/archives/CNJ7KTHQU/p1697805743983069?thread_ts=1697427973.015479&cid=CNJ7KTHQU), now:
- [ ][ replicating those answers in the README file, and 
- [ ] completing the demo with CIP-64 (using CK), and adding ETH legacy, accesslist and dynamic fee transaction (those supported longer-term)

**Comment by 0xarthurxyz** [comment]
Would love a review/read from @nicolasbrugneaux and @shazarre since you're both working on
- https://github.com/celo-org/celo-labs/issues/1022

**Comment by 0xarthurxyz** [comment]
Asked for feedback on "end of life" terminology on [Slack](https://celo-org.slack.com/archives/CNJ7KTHQU/p1698355607630119)

**Comment by 0xarthurxyz** [comment]
Filled bug: 

- https://github.com/celo-org/txtypes/issues/1

**Comment by 0xarthurxyz** [comment]
Repo has moved from [0xarthurxyz/txtypes](https://github.com/0xarthurxyz/txtypes) to [celo-org/txtypes](https://github.com/celo-org/txtypes)

**Comment by nicolasbrugneaux** [comment]
I read this last week and forgot to post feedback, apologies.

I think your repo is very well thought-out and complete, I couldn't discern any major mistake. The one important thing I remember having an issue with was the deprecation notice which I found confusing, but I see you've fixed it already!!

Giga 👍 from me.

**Comment by 0xarthurxyz** [comment]
Closing this ticket. We can always open a new one for improvements.
