### ISSUE TITLE
Alert message update standards

### ISSUE THREAD

**Issue by therealharpaljadeja** [celo-org/docs#1169]
What are the conditions for a message to go out as an alert?

Should we keep the faucet link at the top?

![Image](https://github.com/celo-org/docs/assets/38040789/7f9dc7cd-2b7a-4a0a-a0d4-6a7343b00840)

**Comment by therealharpaljadeja** [comment]
@ericnakagawa how is this?

![Image](https://github.com/celo-org/docs/assets/38040789/de5c22e6-aa76-42b0-a449-476ac58eacf8)

**Comment by 0xarthurxyz** [comment]
I like the faucet call-to-action. Although I don't know how that ranks compared to MiniPay :)
