### ISSUE TITLE
`releasecelo` docs page missing in left-hand index

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/docs#1254]
`releasecelo` docs are available (https://docs.celo.org/cli/releasecelo), but are missing from the left-hand index on docs.celo.org 
<img width="220" alt="image" src="https://github.com/celo-org/developer-tooling/assets/46296830/fda92ee3-240a-4c8e-91ba-3769ee37904b">

_Originally posted by @arthurgousset in https://github.com/celo-org/developer-tooling/issues/151#issuecomment-1964765608_

**Comment by soloseng** [comment]
Might also be worth updating [this](https://docs.celo.org/holder/manage/release-gold) page as well
