### ISSUE TITLE
`holder` section is not shown in the top menu

### ISSUE THREAD

**Issue by lvpeschke** [celo-org/docs#1272]
I noticed that there are quite a few pages under https://docs.celo.org/holder, which are not directly linked in the top menu: 
<img width="980" alt="Screenshot 2024-03-28 at 15 43 57" src="https://github.com/celo-org/docs/assets/4222953/f49ed606-78c0-4fa8-a257-3b2a4732bd1f">

Maybe that's part of the revamp, but in case it isn't, I wanted to flag.

**Comment by therealharpaljadeja** [comment]
Should we change the URL for the holder pages to `/protocol/holder`?

**Comment by therealharpaljadeja** [comment]
> Should we change the URL for the holder pages to `/protocol/holder`?

moved holder to top level in sidebar 

#1276

**Comment by lvpeschke** [comment]
> Should we change the URL for the holder pages to /protocol/holder?

Looking at what's under `/protocol/`, I wouldn't. To me, it looks like `Holder` could be at the same level as `Developer` and `Validator`.
