### ISSUE TITLE
Transferring CELO from Coinbase to Coinbase Wallet

### ISSUE THREAD

**Issue by dl01-crypto** [celo-org/docs#1559]
Does anyone know how to correctly transfer CELO from Coinbase to Coinbase Wallet? I transferred my CELO from Coinbase to Coinbase Wallet...lol...but it vanished. Any idea how to recover CELO.?

**Comment by Annawoody** [comment]
It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID CEL07638
Please see the link below to our dedicated support line:
[Celo Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@dl01-crypto

**Comment by Sophiestanworth** [comment]
> Does anyone know how to correctly transfer CELO from Coinbase to Coinbase Wallet? I transferred my CELO from Coinbase to Coinbase Wallet...lol...but it vanished. Any idea how to recover CELO.?


Hey @dl01-crypto !

I hope your issue is resolved. If not, apologies for the delay! Please contact support with ticket ID CEL7638 for assistance.

Visit [Celo Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat in the bottom right to connect with an agent for quick help.

Thank you for your patience—I hope this is resolved soon!

**Comment by dl01-crypto** [comment]
Hello and to whom it concerns,
I just used the link below to try and retrieve my CELO...but
instead...the site just transferred & removed $3,400 of my crypto to
somewhere that I have no idea where it ended up.?Do you any idea how
this happened? Greatly disappointed in the whole CELO and now this
issue.
Please help
thanks,DL

	-----------------------------------------From: "Sophiestanworth" 
To: "celo-org/docs"
Cc: "dl01-crypto", "Mention"
Sent: Tuesday November 12 2024 7:40:43PM
Subject: Re: [celo-org/docs] Transferring CELO from Coinbase to
Coinbase Wallet (Issue #1559)

	Does anyone know how to correctly transfer CELO from Coinbase to
Coinbase Wallet? I transferred my CELO from Coinbase to Coinbase
Wallet...lol...but it vanished. Any idea how to recover CELO.?  

	Hey @dl01-crypto [1] ! 

	I hope your issue is resolved. If not, apologies for the delay!
Please contact support with ticket ID CEL7638 for assistance. 

	Visit Celo Dapps Support Ticket Requests [2] and use the live chat in
the bottom right to connect with an agent for quick help. 

	Thank you for your patience—I hope this is resolved soon! 

	—
 Reply to this email directly,  view it on GitHub [3], or  unsubscribe
[4].
 You are receiving this because you were mentioned.Message ID:  

Links:
------
[1] https://github.com/dl01-crypto
[2] https://thedappsupport.com/
[3]
https://github.com/celo-org/docs/issues/1559#issuecomment-2472307218
[4]

**Comment by palango** [comment]
Hi @dl01-crypto,
please contact Coinbase support for that issue.
