### ISSUE TITLE
Embed Hubspot Chat to Docs

### ISSUE THREAD

**Issue by joenyzio** [celo-org/docs#423]
`<script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/v2.js"></script>
<script>
 hbspt.forms.create({
   region: "na1",
   portalId: "8568019",
   formId: "062c0387-939a-4a90-b003-70a87065792a"
 });
</script>`

**Comment by jessan-clabs** [comment]
@0xarthurxyz This seems like a really good idea.

**Comment by arthurgousset** [comment]
Did this get done @therealharpaljadeja or is this closed as "not planned"?
