### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by joenyzio** [celo-org/docs#424]
Need to track and fix 404 errors in docs

**Comment by martinvol** [comment]
it often happens after a search, for example 
<img width="667" alt="image" src="https://user-images.githubusercontent.com/698027/189648713-3ec9a822-47c7-4b0c-9684-7e6c53db8d4a.png">

**Comment by nestorbonilla** [comment]
Hi @martinvol, this one should be resolved now. I tried to emulate your search, and it correctly redirects to the page. Feel free to add any additional errors you might find.

**Comment by karlb** [comment]
There are plenty of dead links all over the docs. Here are some examples found by DeadLinkChecker.com:

Error | URL | Anchor Text | Linked From
-- | -- | -- | --
404 Not Found | https://celo.academy/tags/c/tutorials/4 | Developer Tutorials | https://docs.celo.org/developer
-1 Timeout | https://alities.io/ |   | https://docs.celo.org/showcase
-1 Timeout | https://ariswap.co/ |   | https://docs.celo.org/showcase
-1 Not found: An error occurred in the secure channel support | https://docs.bitwage.com/ | source | https://docs.celo.org/showcase
-1 Not found: The server name or address could not be resolved | https://celo.dance/ |   | https://docs.celo.org/showcase
402 Payment Required | https://www.coperacha.app/ |   | https://docs.celo.org/showcase
-1 Not found: The server name or address could not be resolved | https://www.emergingimpact.com/ |   | https://docs.celo.org/showcase
403 Forbidden | https://niftydrop.net/ |   | https://docs.celo.org/showcase
-1 Not found: The server name or address could not be resolved | https://celo-wallet.paychant.com/ |   | https://docs.celo.org/showcase
-1 Not found: The server name or address could not be resolved | https://paysail.us/ |   | https://docs.celo.org/showcase
-1 Not found: The server name or address could not be resolved | https://poof.cash/ |   | https://docs.celo.org/showcase
-1 Not found: The server name or address could not be resolved | https://epor.io/ |   | https://docs.celo.org/showcase
-1 Not found: The server name or address could not be resolved | https://qavah.me/ |   | https://docs.celo.org/showcase
-1 Timeout | https://celo-pools.symmetric.exchange/ |   | https://docs.celo.org/showcase
-1 Not found: The server name or address could not be resolved | https://tegger.io/ |   | https://docs.celo.org/showcase
-1 Not found: A connection with the server could not be established | https://www.athena.tech/ |   | https://docs.celo.org/showcase
-1 Not found: An error occurred in the secure channel support | https://www.kolorapp.com/ |   | https://docs.celo.org/showcase
404 Not Found | https://celo.org/build/wallet | Celo Wallet | https://docs.celo.org/network
404 Not Found | https://celo.org/build/faucet | obtain a balance | https://docs.celo.org/network
404 Not Found | https://figment.io/datahub/celo/ | Figment Datahub | https://docs.celo.org/developer/migrate/from-ethereum
404 Not Found | https://docs.celo.org/blog/developer-guide/start/hellocontracts | This tutorial | https://docs.celo.org/developer/migrate/from-ethereum
404 Not Found | https://docs.celo.org/blog/developer-guide/start/hello-contract-remote-node | This tutorial | https://docs.celo.org/developer/migrate/from-ethereum
-1 Not found: The server name or address could not be resolved | https://docs.ethhub.io/ | EthHub.io | https://docs.celo.org/developer/evm-tools
404 Not Found | https://dapp.tools/dapp/ | Dapp | https://docs.celo.org/developer/evm-tools
404 Not Found | https://docs.epirus.io/sdk/ | Epirus | https://docs.celo.org/developer/evm-tools
404 Not Found | https://marketplace.visualstudio.com/items?itemName=quantanetwork.ethcode | Ethcode | https://docs.celo.org/developer/evm-tools
404 Not Found | https://marketplace.visualstudio.com/items?itemName=AzBlockchain.azure-blockchain | Azure Blockchain Dev Kit for Ethereum for VSCode | https://docs.celo.org/developer/evm-tools
404 Not Found | https://besu.hyperledger.org/en/stable/Tutorials/Quickstarts/Azure-Private-Network-Quickstart/ | Besu Private Network | https://docs.celo.org/developer/evm-tools
-1 Timeout | https://faucet.rinkeby.io/ | Rinkeby faucet | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://faucet.metamask.io/ | Ropsten faucet (MetaMask) | https://docs.celo.org/developer/evm-tools
-1 Timeout | https://faucet.rpanic.com/ | Ropsten faucet (rpanic) | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://faucets.blockxlabs.com/ | Universal faucet | https://docs.celo.org/developer/evm-tools
404 Not Found | https://0x.org/docs/tools/subproviders | Subproviders | https://docs.celo.org/developer/evm-tools
429 Too Many Requests | https://github.com/ticket721/ethvtx | ethvtx | https://docs.celo.org/developer/evm-tools
404 Not Found | https://ticket721.github.io/ethvtx/ | docs | https://docs.celo.org/developer/evm-tools
429 Too Many Requests | https://github.com/mesg-foundation/service-ethereum-contract | Ethereum Contract Service | https://docs.celo.org/developer/evm-tools
429 Too Many Requests | https://github.com/mesg-foundation/service-ethereum | Ethereum Service | https://docs.celo.org/developer/evm-tools
-1 Not found: The host name in the certificate is invalid or does not match | https://marmo.io/ | Marmo | https://docs.celo.org/developer/evm-tools
404 Not Found | https://blog.aragon.org/tag/research/ | Aragon research blog | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://swarm-gateways.net/ | Swarm | https://docs.celo.org/developer/evm-tools
404 Not Found | https://docs.3box.io/api/storage | 3Box Storage | https://docs.celo.org/developer/evm-tools
404 Not Found | https://docs.3box.io/api/messaging | 3Box Threads | https://docs.celo.org/developer/evm-tools
404 Not Found | https://trufflesuite.com/teams | Truffle Teams | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://securify.chainsecurity.com/ | Securify | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://tool.smartdec.net/ | SmartCheck | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://aleth.io/ | Alethio | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://scout.cool/ | Scout | https://docs.celo.org/developer/evm-tools
-1 Not found: The host name in the certificate is invalid or does not match | https://www.chainlyt.io/main/dashboard/contract | Chainlyt | https://docs.celo.org/developer/evm-tools
429 Too Many Requests | https://github.com/mesg-foundation/service-plasma-omisego-watcher | Plasma OmiseGo Watcher | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://bridge.poa.net/ | POA Bridge | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://docs.matic.network/ | Matic Network | https://docs.celo.org/developer/evm-tools
-1 Not found: The server name or address could not be resolved | https://components.bounties.network/ | components.bounties.network | https://docs.celo.org/developer/evm-tools
404 Not Found | https://github.com/MetaMask/metamask-extension/tree/develop/ui/app/components | Metamask ui | https://docs.celo.org/developer/evm-tools
404 Not Found | https://docs.3box.io/build/plugins | 3Box Plugins | https://docs.celo.org/developer/evm-tools
404 Not Found | https://celo.org/buy | Celo Owners | https://docs.celo.org/holder
404 Not Found | https://github.com/celo-org/docs/tree/main/blog | blog directory | https://docs.celo.org/community/guidelines
404 Not Found | https://images.ctfassets.net/bzlah72jow8z/bmyoV7T0sEJTJlcTkvL18/de50fc80b518f648ed94f8decf03c03c/MOR-desktop.jpg | style: .hero--primary | https://docs.celo.org/assets/css/styles.94b24baf.css
404 Not Found | https://github.com/celo-org/celo-monorepo/blob/master/packages/attestation-service/config/.env.development | template Attestation Service config file | https://docs.celo.org/validator/attestation
503 Service Unavailable | https://metabase.celo-networks-dev.org/public/dashboard/b0a27650-1d62-4645-81d7-26ff7546ff0d?date_filter=past2weeks~ | Attestation Service Dashboard | https://docs.celo.org/validator/attestation
404 Not Found | https://github.com/celo-org/celo-monorepo/blob/master/packages/attestation-service/src/index.ts | limited number of paths | https://docs.celo.org/validator/security
404 Not Found | https://www.gitcoin.co/celo-org/projects | Bounties [301 from https://gitcoin.co/celo-org/projects] | https://docs.celo.org/community/celo-sage
404 Not Found | https://pandapay.ca/en/ | https://www.pandapay.ca/en/ [301 from https://www.pandapay.ca/en/] | https://docs.celo.org/wallet
404 Not Found | https://www.openzeppelin.com/starter-kits/ | OpenZeppelin Starter Kits [301 from https://openzeppelin.com/starter-kits/] | https://docs.celo.org/developer/evm-tools
404 Not Found | https://openethereum.github.io/wiki/Demo-PoA-tutorial.html | Parity Demo-PoA Tutorial [301 from https://wiki.parity.io/Demo-PoA-tutorial.html] | https://docs.celo.org/developer/evm-tools
404 Not Found | https://docs.venly.io/widget/pages/connect-js.html | Arkane Connect [302 from https://docs.arkane.network/pages/connect-js.html] | https://docs.celo.org/developer/evm-tools
404 Not Found | https://learn.microsoft.com/en-us/windows/wsl/initialize-distro | here [301 from https://docs.microsoft.com/en-us/windows/wsl/initialize-distro] | https://docs.celo.org/developer/setup/windows
403 Forbidden | https://www.crunchbase.com/ | https://www.crunchbase.com/ | https://docs.celo.org/community/fundraising
404 Not Found | https://angels.firstround.com/directory | https://angels.firstround.com/directory | https://docs.celo.org/community/fundraising
404 Not Found | https://opencelo.gitbook.io/mobius/ | Contracts | https://docs.celo.org/integration/dapps
-1 Not found: The server name or address could not be resolved | https://www.dahlia.finance/earn | Pinnata | https://docs.celo.org/integration/dapps
-1 Not found: The server name or address could not be resolved | https://www.resourcenetwork.co/ | Resource | https://docs.celo.org/integration/dapps
404 Not Found | https://github.com/ReSource-Network/ | GitHub | https://docs.celo.org/integration/dapps
404 Not Found | https://github.com/cybertime-eth/CyberBox-NFT-Marketplace/tree/main/contracts | Contracts | https://docs.celo.org/integration/dapps
404 Not Found | https://www.notion.so/talentprotocol/Talent-Protocol-101-26a6c4b9f8284e5e8f55603a38629e76 | About us | https://docs.celo.org/integration/dapps
-1 Not found: The host name in the certificate is invalid or does not match | https://neftme.com/ | NEFTME | https://docs.celo.org/integration/dapps
-1 Not found: An error occurred in the secure channel support | https://thenode.fi/hackathon | Berkeley Blockchain Hackathon | https://docs.celo.org/integration/dapps
404 Not Found | https://github.com/celo-org/celo-monorepo/tree/master/packages/cli/src/commands/account/claim-attestation-service-url.ts | src/commands/account/claim-attestation-service-url.ts | https://docs.celo.org/cli/account

**Comment by karlb** [comment]
There's also the list of broken links that docusaurus prints at every build:

```
[WARNING] Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /pt/developer/contractkit/usage:
   -> linking to /pt/blog/developer-guide/start/hellocontracts

- On source page path = /pt/developer/dappkit:
   -> linking to /pt/blog/2022/01/08/valora-wc-v1

- On source page path = /pt/developer/dappkit/usage:
   -> linking to /pt/developer-guide/contractkit

- On source page path = /pt/developer/migrate/from-ethereum:
   -> linking to /pt/blog/developer-guide/start/hellocontracts
   -> linking to /pt/blog/developer-guide/start/hello-contract-remote-node

- On source page path = /pt/developer/tools:
   -> linking to /pt/blog/using-the-graph

- On source page path = /pt/developer/verify/hardhat:
   -> linking to /pt/blog/hardhat-deploy-verify

- On source page path = /pt/developer/walkthrough/no-code-erc20:
   -> linking to /pt/blog/add-token-celo-wallet

- On source page path = /pt/learn/developer-onboarding:
   -> linking to /pt/blog/2022/01/07/on-chain-randomness
   -> linking to /pt/blog/2022/01/08/valora-wc-v1

- On source page path = /pt/learn/developer-tools:
   -> linking to /pt/blog/using-the-graph

- On source page path = /pt/network/alfajores:
   -> linking to /pt/important-information/alfajores-testnet-disclaimer

- On source page path = /pt/network/node/forno:
   -> linking to /pt/blog/developer-guide/start/hellocelo

- On source page path = /pt/protocol/governance:
   -> linking to ../../community/release-process/smart-contracts (resolved as: /community/release-process/smart-contracts)

- On source page path = /pt/wallet:
   -> linking to /pt/blog/tutorials/celo-valora-and-walletconnect-v1
```

**Comment by karlb** [comment]
Running a link checker still finds plenty of dead links most of them are links to external projects, but far from all of them. There's even a dead ambassadors link right on the https://docs.celo.org/ home page. Do we have any plan how to deal with the dead links?
