### ISSUE TITLE
Update banner and footer color

### ISSUE THREAD

**Issue by joenyzio** [celo-org/docs#558]
New colors look amazing but kind of conflict with the previous banner and footer colors that haven't been updated. The gray used for the boxes on the home page would probably look nice or maybe a different color available in the branding.

**Comment by ericnakagawa** [comment]
Can you include this string in the list of strings that can be localized?

**Comment by nestorbonilla** [comment]
Updates:

- The home page has been updated with new brand colors. (solved on [PR #563](https://github.com/celo-org/docs/pull/563))
