### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by FurcasM** [celo-org/docs#575]
Hello. I am a user of the Telegram app and I want to know if you have any agreement, page or airdrop on this social network. Good for the alliance with Good Dollar

**Comment by nestorbonilla** [comment]
Hi @FurcasM,

I'm not sure what you're referring to, but you can join the [Celo Discord Server](https://chat.celo.org/) and ask there.
Feel free to open an issue, but only regarding a Celo Documentation improvement or suggestion.
