### ISSUE TITLE
Publish blog post about "recommended architecture for a simple payment dapp"

### ISSUE THREAD

**Issue by 0xarthurxyz** [celo-org/docs#662]
[Definition of done](https://www.notion.so/clabsco/Formulate-a-recommended-tooling-stack-for-a-simple-web-app-and-a-simple-mobile-app-based-on-feedback-c8352960112d42659af16981d210704e) (Notion)

**Comment by nicolasbrugneaux** [comment]
WIP #699

**Comment by nicolasbrugneaux** [comment]
Merged, will be published Monday (2023-03-06)
